# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 40, 113, 32))
        self.pushButton.setObjectName("BtnLoad")
        self.BtnRefresh = QtWidgets.QPushButton(self.centralwidget)
        self.BtnRefresh.setGeometry(QtCore.QRect(290, 40, 113, 32))
        self.BtnRefresh.setObjectName("BtnRefresh")
        self.BtnSave = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSave.setGeometry(QtCore.QRect(90, 40, 113, 32))
        self.BtnSave.setObjectName("BtnSave")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 90, 641, 341))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(14)
        self.tableWidget.setHorizontalHeaderLabels(
            ["uid", "name", "tm_type", "energy_object", "create_date", "quality_code", "code_desc", "value",
             "entry_point", "author",
             "duration", "raw_date", "raw_quality_code", "raw_value"])
        self.tableWidget.setRowCount(100)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.data_load()


    def retranslateUi(self, MainWindow):

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.BtnRefresh.setText(_translate("MainWindow", "Обновить"))
        self.BtnSave.setText(_translate("MainWindow", "Сохранить"))
        self.actionabout.setText(_translate("MainWindow", "file"))


    def data_load(self):

        connection = sqlite3.connect("smqt.db")
        cursor = connection.cursor()
        sql_query = '''SELECT * FROM smqt'''
        table_row = 0
        for i in cursor.execute(sql_query):
            self.tableWidget.setItem(table_row, 0, QtWidgets.QTableWidgetItem(i[0]))
            self.tableWidget.setItem(table_row, 1, QtWidgets.QTableWidgetItem(i[1]))
            self.tableWidget.setItem(table_row, 2, QtWidgets.QTableWidgetItem(i[2]))
            self.tableWidget.setItem(table_row, 3, QtWidgets.QTableWidgetItem(i[3]))
            self.tableWidget.setItem(table_row, 4, QtWidgets.QTableWidgetItem(i[4]))
            self.tableWidget.setItem(table_row, 5, QtWidgets.QTableWidgetItem(i[5]))
            self.tableWidget.setItem(table_row, 6, QtWidgets.QTableWidgetItem(i[6]))
            self.tableWidget.setItem(table_row, 7, QtWidgets.QTableWidgetItem(i[7]))
            self.tableWidget.setItem(table_row, 8, QtWidgets.QTableWidgetItem(i[8]))
            self.tableWidget.setItem(table_row, 9, QtWidgets.QTableWidgetItem(i[9]))
            self.tableWidget.setItem(table_row, 10, QtWidgets.QTableWidgetItem(i[10]))
            self.tableWidget.setItem(table_row, 11, QtWidgets.QTableWidgetItem(i[11]))
            self.tableWidget.setItem(table_row, 12, QtWidgets.QTableWidgetItem(i[12]))
            self.tableWidget.setItem(table_row, 13, QtWidgets.QTableWidgetItem(i[13]))

            table_row += 1
        connection.close()